export const SOCKET_EVENTS = {
  ANNOUNCEMENT_CREATED: "announcement:created",
  TICKET_CREATED: "ticket:created",
  TICKET_STATUS_UPDATED: "ticket:status_updated",
  EVENT_CREATED: "event:created",
  EVENT_UPDATED: "event:updated",
  EVENT_DELETED: "event:deleted",
  AMENITY_CREATED: "amenity:created",
  AMENITY_BOOKING_CREATED: "amenity:booking_created",
  AMENITY_BOOKING_STATUS_UPDATED: "amenity:booking_status_updated",
  MEMBERSHIP_APPROVED: "membership:approved",
  MEMBERSHIP_REJECTED: "membership:rejected",
  NOTIFICATION_CREATED: "notification:created",
  VISITOR_REQUEST_INCOMING:  "visitor:request_incoming",
  VISITOR_REQUEST_RESPONDED: "visitor:request_responded",
  VISITOR_PRE_REG_USED:      "visitor:prereg_used",
  FREQ_VISITOR_ENTRY:        "visitor:freq_entry",
  GROUP_PASS_USED:           "visitor:group_pass_used",
  STAFF_ENTRY:               "staff:entry",
  STAFF_LEAVE_TOGGLED:       "staff:leave_toggled",
  POLL_CREATED:              "poll:created",
  POLL_UPDATED:              "poll:updated",
  POLL_DELETED:              "poll:deleted",
};
